---
apiVersion: v1
kind: Service
metadata:
  name: humio-tcp-listener
  namespace: "$NAMESPACE_HUMIO"
spec:
  selector:
    app.kubernetes.io/instance: humio-cluster
    app.kubernetes.io/managed-by: humio-operator
    app.kubernetes.io/name: humio
  ports:
    - name: tcp-listener
      port: 514
      targetPort: 514
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: humio-tcp-listener
  namespace: "$NAMESPACE_HUMIO"
spec:
  port:
    targetPort: tcp-listener
  to:
    kind: Service
    name: humio-tcp-listener
    weight: 100
